#main args
adam_beta1: 0.9
adam_beta2: 0.999
decay_factor: 0.9
config_files: ./config/
dataset: QKA
eval_freq: 5
init_std: 0.02
log_freq: 1
min_lr: 1.0e-06
output_dir: ./output
patience: 5
run_dir: ./run
weight_decay: 0.0
maxlen: 50





